title: <p align="center"> Kitipat Wararungsriroj </p>

logo: "files/S__69017665_01.jpg"

description: |
  <p align="center">
    <a href="files/CV.pdf" download>Download CV</a> |
    <a href="https://github.com/KitipatWararungsriroj">GitHub</a> |
    <a href="https://www.linkedin.com/in/kitipat-wararungsriroj-129881337">LinkedIn</a> |
  </p>

  <p align="justify">
       I am a recent Statistics graduate (GPA 3.44, Second-Class Honors) with a strong interest in data analytics and applying statistical methods to solve problems.
theme: jekyll-theme-minimal
